export * from './ArticlesTemplate'
export * from './ForgotPasswordTemplate'
export * from './HomeTemplate'
export * from './LoginTemplate'
export * from './NewArticleTemplate'
export * from './ArticleTemplate'
export * from './ProfileTemplate'
export * from './RegisterUserTemplate'
